class OBDData(BaseModel):
    TIMESTAMP: float
    MARK: str
    CAR_YEAR: float
    MODEL: str
    ENGINE_POWER: str
    AUTOMATIC: str
    VEHICLE_ID: str
    BAROMETRIC_PRESSURE: float
    ENGINE_COOLANT_TEMP: float
    FUEL_LEVEL: str
    ENGINE_LOAD: str
    AMBIENT_AIR_TEMP: float
    ENGINE_RPM: float
    INTAKE_MANIFOLD_PRESSURE: float
    MAF: str
    LONG_TERM_FUEL_TRIM_BANK_2: str
    FUEL_TYPE: str
    AIR_INTAKE_TEMP: float
    FUEL_PRESSURE: float
    SPEED: float
    SHORT_TERM_FUEL_TRIM_BANK_2: str
    SHORT_TERM_FUEL_TRIM_BANK_1: str
    ENGINE_RUNTIME: str
    THROTTLE_POS: str
    DTC_NUMBER: str
    TROUBLE_CODES: str
    TIMING_ADVANCE: str
    EQUIV_RATIO: str
    MIN: float
    HOURS: float
    DAYS_OF_WEEK: float
    MONTHS: float
    YEAR: float
